// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from 'D:/project/stock_py/frontend/src/.umi/plugin-access';
export { Provider, useModel } from 'D:/project/stock_py/frontend/src/.umi/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from 'D:/project/stock_py/frontend/src/.umi/plugin-request';
// plugins types.d.ts
export * from 'D:/project/stock_py/frontend/src/.umi/plugin-access/types.d';
export * from 'D:/project/stock_py/frontend/src/.umi/plugin-antd/types.d';
export * from 'D:/project/stock_py/frontend/src/.umi/plugin-layout/types.d';
export * from 'D:/project/stock_py/frontend/src/.umi/plugin-request/types.d';
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from 'D:/project/stock_py/frontend/node_modules/.pnpm/@umijs+renderer-react@4.6.6_f8bb1566470238dad1cab5ef97d093f7/node_modules/@umijs/renderer-react';
export type { History, ClientLoader } from 'D:/project/stock_py/frontend/node_modules/.pnpm/@umijs+renderer-react@4.6.6_f8bb1566470238dad1cab5ef97d093f7/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from 'D:/project/stock_py/frontend/node_modules/.pnpm/umi@4.6.67_@babel+core@7.29_d3dbad258dc026af2d8d955f16d00e46/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
// test
export { TestBrowser } from './testBrowser';
