// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import { HelmetProvider } from 'D:/project/stock_py/frontend/node_modules/.pnpm/@umijs+renderer-react@4.6.6_f8bb1566470238dad1cab5ef97d093f7/node_modules/@umijs/renderer-react';
import { context } from './helmetContext';

export const innerProvider = (container) => {
  return React.createElement(HelmetProvider, { context }, container);
}
